### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by mehalick** [mehalick/Xaki#4]
I'm very curious to know how the various `Localize()` methods perform and want to establish some baselines to see how changes affect performance. I'd like to integrate something like https://github.com/dotnet/BenchmarkDotNet to begin collecting data.

**Comment by ghost** [comment]
I have worked with BenchmarkDotNet before, it's quite fun actually, you should get your hands on it ASAP. Let me know if you need any pointers in it.

**Comment by mehalick** [comment]
Implemented in v0.0.6
