### ISSUE TITLE
Check EF dynamic proxy without type.Namespace == "System.Data.Entity.DynamicProxies

### ISSUE THREAD

**Issue by ghost** [mehalick/Xaki#9]
```
        private IEnumerable<PropertyInfo> GetProperties<T>(T item) where T : class, ILocalizable
        {
            var type = typeof(T);
            if (type == typeof(ILocalizable))
            {
                type = item.GetType();
            }

            return _propertyCache.GetOrAdd(type, _ => type.GetTypeInfo().DeclaredProperties);
        }
```

I believe this would eliminate the need to check the namespace of the type when using  ILocalizable with EF dynamic proxies. This would also pass all existing unit tests.

**Note I haven't actually tested this (outside of the existing unit tests)! But I think It should work**

Note that dynamic proxies are used when

- Change Tracking is Enabled
- LazyLoading is Enabled

and they inherit from the actual entity defined in the system.

By the way if you check the [source reference](https://referencesource.microsoft.com/#System.Data.Entity/System/Data/Objects/ObjectContext.cs,56a679f261d7791d,references) of `ObjectContext.GetObjectType` you are not far of of the native implementation

That being said If we could have unit tests for

- EF
- EF Core
- POCOs (which is what we have now)

That would awesome.

Aside: `_propertyCache` should be a `private **static** readonly`

**Comment by mehalick** [comment]
I confirm this works across all EF scenarios and have updated.

Unit testing EF is on my mental roadmap but I'm not sure how to actually do this without creating an actual EF project with database.

EF Core could be done with an in-memory database,.. need to determine the effort and value.

I also updated to add the C# 7.2 "in" keyword per https://github.com/Tarek-Samy/Xaki/pull/19 and will benchmark shortly. 

I wasn't able to add the `T` --> `object` optimizations because `GetProperties<T>` must stay generic with this update. If you'd like to take another look please let me know what you think we can do.

**Comment by mehalick** [comment]
Ok I actually had to revert the update to `GetProperties<T>`, when fetching a single item it failed to localize navigation properties and reverting resolved. I need to debug and see why, will try to restore as soon as I find the issue.

**Comment by ghost** [comment]
I'm sorry if I miss understand but

```
            var type = typeof(T);
            if (type == typeof(ILocalizable))
            {
                type = item.GetType();
            }
```

Worked then it stopped working? Or it just didn't work in specific situations?

Apologies if this wasted time, as I said I didn't test it on EF or EF Core because setting it up is a nascence as you said. But my MAD CODE SKILLZ told me that it should work.

Anyway keep me updated on this please, and I'll check as soon as I can. 

I suggest when debugging, to disable the properties dictionary cache. 

One drawback from adding `in` on the interface level. Is that if the library is released (which I think you plan on doing anyway), and someone wanted to implement their own `IObjectLocalizer` they will have to do that in a project that supports 7.2 or higher. And maybe they have limitations on that part. Just something to think about anyway.

For EF testing, the part I care about more is ProxyTypes and Regular EntityTypes so I don't really care about actually getting items from database, I would want to be able to create a ProxyType and EntityType in memory and try to serialize them which is actually the case this library  is covering working with Entities and Proxies in memory.

For EF Core as you said we can use InMemory or just something similar to what I described above. Just a list of Proxies and Entities without actually making a connection to the db. 

Proxies can be created by Reflection in RunTime, and we can always just create an instance of an entity (which actually is just going to get the POCO treatment, so I'm not worried about that.)

**Comment by ghost** [comment]
@mehalick I guess most likely the reason it fails to get properties is because `Proxies` are derived from the actual entity types and we use `type.GetTypeInfo().DeclaredProperites` and the proxy type doesn't actually have any declared properties that are `Localizable`. They are all inherited from the base type. I'm 99% sure that if you change that line to `type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.GetProperty)` localization would work with the change I proposed. Better yet if you read on, you don't even need the change I proposed earlier that uses `typeof(T)`, or the "Hack" to know the namespace. We can just use `item.GetType()` always but we need to introduce three very small changes:

1. Keep the new proposed way of reading properties: `type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.GetProperty)`
2. Change `[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]` to `[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]` on the `LocalizedAttribute`
3. Read the type of item with just `item.GetType()` with nothing extra

And here is why:

### 1
`type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.GetProperty)` Gets the properties of an object whether they were inherited or declared (where declared means that they were actually defined by the object).

### 2
So with that being said, I have been thinking a little bit more about proxy types and came to the conclusion that *I* have been looking at the problem in the wrong way.
As stated proxies just derive i.e., inherit the entity (hence the usage of `type.BaseType` if the namespace of the entity is a proxy), where you try to treat the proxy type as your main entity, just so you can read the properties, but we actually don't need that at all.
If you look at the `Localized` attribute you will see it defined as `[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]` *Inherited = false* which basically disallows any class that inherits another that implement the `ILocalizable` interface from having the `Localizaed` attribute on the inherited properties. So in the case of proxies, you get proxies with no Attributes on the properties, and that's why they fail in the original place. If we change `Inherited  = true` proxies will work 100% out of the box with no need to extra checking of the namespace or changing anything because now the attributes are inhered.

### 3
`item.GetType()` gets the actual runtime type of an object, proxies, entities or POCOs we only care about that type not the base since attributes are going to be inherited.

**Comment by ghost** [comment]
FYI all be adding some additional test cases and "Proxies" that validate all that. But I think you get the gist of it without the need to do so.
